name: Build and Deploy to Cloud Run

on:
    push:
        branches:
            - "main"

env:
    PROJECT_ID: ${{ secrets.PROJECT_ID }}
    REPOSITORY: ${{secrets.TOKEN_SCANNER_REPOSITORY}}
    SERVICE: ${{ secrets.SERVICE }}
    REGION: ${{ secrets.TOKEN_SCANNER_REGION }}

jobs:
    deploy:
        # Add 'id-token' with the intended permissions for workload identity federation
        permissions:
            contents: "read"
            id-token: "write"

        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Google Auth
              id: auth
              uses: "google-github-actions/auth@v2"
              with:
                  token_format: "access_token"
                  workload_identity_provider: "${{ vars.WIF_PROVIDER }}" # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
                  service_account: "${{ vars.WIF_SERVICE_ACCOUNT }}" # e.g. - my-service-account@my-project.iam.gserviceaccount.com

            - name: Docker Auth
              uses: docker/login-action@v3
              with:
                  username: "oauth2accesstoken"
                  password: "${{ steps.auth.outputs.access_token }}"
                  registry: "${{ env.REGION }}-docker.pkg.dev"

            - name: Build and Push Container
              run: |-
                  docker build -t "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}" ./
                  docker push "${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}"

            # END - Docker auth and build

            - name: Deploy to Cloud Run
              id: deploy
              uses: google-github-actions/deploy-cloudrun@v0
              with:
                  service: ${{ env.SERVICE }}
                  region: ${{ env.REGION }}
                  image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE }}:${{ github.sha }}
                  flags: |
                      --no-allow-unauthenticated
                  env_vars: |
                      RPC_URL=${{secrets.RPC_URL}}
                      RPC_URL_WSS=${{secrets.RPC_URL_WSS}}
                      TELOXIDE_TOKEN=${{secrets.TELOXIDE_TOKEN}}
                      ETHERSCAN_API_KEY=${{secrets.ETHERSCAN_API_KEY}}

            # If required, use the Cloud Run url output in later steps
            - name: Show Output
              run: echo ${{ steps.deploy.outputs.url }}
